# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('heartbeat', models.IntegerField()),
                ('heartbeat_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'User Beat',
                'verbose_name_plural': 'Users Beats',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('emailaddress_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profile',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('temperature', models.IntegerField()),
                ('temperature_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'User Temperature',
                'verbose_name_plural': 'Users Temperatures',
            },
        ),
    ]
