# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0002_auto_20180224_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='cellphone1',
            field=models.CharField(default='000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='cellphone2',
            field=models.CharField(default='000000000', max_length=11),
        ),
    ]
