# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0007_auto_20180305_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
