# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0008_auto_20180305_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temperature',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='heartbeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='heartbeat_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
