# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0009_auto_20180305_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='temperature_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
