# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0010_auto_20180306_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='heartbeat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
