# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0012_auto_20180523_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
