# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0013_remove_profile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'More info', 'verbose_name_plural': 'More infos'},
        ),
    ]
