# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0014_auto_20180524_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'More user info', 'verbose_name_plural': 'More user infos'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emailaddress_name',
        ),
    ]
