# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0016_auto_20180529_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cellphone1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cellphone2',
        ),
        migrations.AddField(
            model_name='profile',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_for_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
