# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0018_heartbeatdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate_reading', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HeartBeatData',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_for_data',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='heartratedata',
            name='data_from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthMonitoring.Profile'),
        ),
    ]
