# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0023_auto_20180530_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartratedata',
            name='time_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='time_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
