# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0024_auto_20180603_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartratedata',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='data_recorded',
        ),
    ]
