# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0025_auto_20180603_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartratedata',
            name='status',
            field=models.CharField(choices=[('EB', 'Excellent'), ('GB', 'Good'), ('AA', 'Above Average'), ('AB', 'Average'), ('BA', 'Below Average'), ('PB', 'Poor')], default='GB', max_length=6),
        ),
    ]
