# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthMonitoring', '0027_temperaturedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='temperature_reading',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
